# Generated by Django 4.0 on 2023-06-09 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exampleapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Location Name', max_length=250)),
                ('latitude', models.CharField(help_text='Location latitude', max_length=100)),
                ('longitude', models.CharField(help_text='Location longitude', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file_field', models.FileField(blank=True, null=True, upload_to='media_files/')),
                ('end_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='end_tickets', to='exampleapp.location')),
                ('start_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start_tickets', to='exampleapp.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exampleapp.user')),
            ],
        ),
    ]
