# Generated by Django 4.0 on 2023-06-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exampleapp', '0005_rename_travale_date_ticket_travel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='travel_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
