# Generated by Django 4.0 on 2023-06-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exampleapp', '0006_alter_ticket_travel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='travel_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
